//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Khusnullin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int idOrderProduct { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> idOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
