//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Khusnullin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int idSotrudnik { get; set; }
        public string FIO { get; set; }
        public string Addres { get; set; }
        public Nullable<double> Phone { get; set; }
        public Nullable<double> Pasport { get; set; }
        public Nullable<int> idOtdel { get; set; }
        public Nullable<int> idStaff { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Otdel Otdel { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
